### ISSUE TITLE
why nuget not work in vs2017 15.3 preview（2）

### ISSUE THREAD

**Issue by chiglish** [Knowzy/KnowzyInternalApps#1]
last firday，at the Beijing Build Tour，I git the project works well。but i update my vs2017 to 15.3 preview，most of nuget extention said “在此资源不可用”，i don‘t know the error in english..i can't compile the project。。
i git the project it still doesnt work....

Compatibility Issues？
![image](https://user-images.githubusercontent.com/7542359/27060592-88918c2e-5010-11e7-97e4-bd8ffe896550.png)

**Comment by nmetulev** [comment]
Never ran into this issue. Can you share what your package sources look like (Tools -> NuGet Package Manager -> Package Manager Settings -> Package Sources)?

**Comment by chiglish** [comment]
this is my setting
![Uploading image.png…]()

**Comment by chiglish** [comment]
new windows，new vs 2017 preview i installed,this is my setting
<img width="581" alt="nugetsources" src="https://user-images.githubusercontent.com/7542359/27061359-dbfedc2c-5015-11e7-91d4-4e5677c8ffda.PNG">

i seems something wrong with my network?but i change another still not work

![image](https://user-images.githubusercontent.com/7542359/27061550-87ceaaf4-5017-11e7-9699-868b701bb1e3.png)

**Comment by chiglish** [comment]
same network，i tryed vs2017 15.2，the project works well，nuget works well。i will remove the preview edition until stable。。。thanks

**Comment by nmetulev** [comment]
Let us know how it works out. I'll close out this issue.
